# Generated by Django 5.1.6 on 2025-03-10 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipe_created_on_recipe_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_name', to='ledger.profile'),
        ),
    ]
