# Generated by Django 5.1.6 on 2025-03-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_recipeimage_uploader_alter_recipeimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
